#!/bin/bash

#PBS -N d2q9-bgk
#PBS -j oe
#PBS -o d2q9-bgk.out
#PBS -q teaching
#PBS -l nodes=1:ppn=16:gpus=1,walltime=00:10:00

# Change the working directory (default is home directory)
cd "$PBS_O_WORKDIR"

module load cuda/toolkit/7.5.18

# Select the GPU that we've been allocated
device=$(cat $PBS_GPUFILE)
device=${device#*gpu}
export OCL_DEVICE=$device

echo "Running on host: $(hostname)"
echo "Time is: $(date)"
echo "Directory is: $(pwd)"
echo "PBS job ID is: $PBS_JOBID"
echo "This jobs runs on the following machines: $(cat "$PBS_NODEFILE" | uniq)"
echo "GPU selected: $OCL_DEVICE"
echo

for SIZE in "128x128" "128x256" "256x256";
do
  ./d2q9-bgk input_${SIZE}.params obstacles_${SIZE}.dat
  python check/check.py --ref-av-vels-file=check/${SIZE}.av_vels.dat --ref-final-state-file=check/${SIZE}.final_state.dat --av-vels-file=./av_vels.dat --final-state-file=./final_state.dat
done
